/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import Clases.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author reydi
 */
public class frmVentana extends javax.swing.JFrame {

    /**
     * Creates new form frmVentana
     */
    public frmVentana() {
        initComponents();
        setExtendedState(MAXIMIZED_BOTH);
        llenarCliente();
        llenarPersona();
        llenarMascota();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cliente = new javax.swing.JDialog();
        lblGenero = new javax.swing.JLabel();
        txtCliente = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        cbGenero = new javax.swing.JComboBox();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblCliente = new javax.swing.JLabel();
        btnElimar = new javax.swing.JButton();
        Persona = new javax.swing.JDialog();
        txtTelefono = new javax.swing.JTextField();
        txtClientePer = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtDirecion = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnAceptarPersona = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnCancelarPersona = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblCliente1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnAgregarCliente = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblListaPersona = new javax.swing.JTable();
        txtBuscarPersona = new javax.swing.JTextField();
        btnBuscarPersona = new javax.swing.JButton();
        btnEliminarPersona = new javax.swing.JButton();
        btnSiguientePersona = new javax.swing.JButton();
        Mascota = new javax.swing.JDialog();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtClienteMas = new javax.swing.JTextField();
        txtTipoAnimal = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        btnAceptarMascota = new javax.swing.JButton();
        btnCancelarMascota = new javax.swing.JButton();
        txtNombreMascota = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblListaMascota = new javax.swing.JTable();
        btnEliminarMascota = new javax.swing.JButton();
        btnFinalizarMascota = new javax.swing.JButton();
        txtBuscarMascota = new javax.swing.JTextField();
        btnBuscarMascota = new javax.swing.JButton();
        cbEdad = new javax.swing.JComboBox();
        ListaCliente = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblListaCliente = new javax.swing.JTable();
        btnEliminar = new javax.swing.JButton();
        btnAgregarCl = new javax.swing.JButton();
        btnCerrarCl = new javax.swing.JButton();
        lblTitulo = new javax.swing.JLabel();
        txtBuscarCliente = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        Consulta_Persona = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        txtResultadoPersona = new javax.swing.JTextArea();
        lblTotulop = new javax.swing.JLabel();
        btnAceptarConsulta = new javax.swing.JButton();
        Consultar_Mascota = new javax.swing.JDialog();
        jScrollPane5 = new javax.swing.JScrollPane();
        txtResultadoMascota = new javax.swing.JTextArea();
        lblTotulo = new javax.swing.JLabel();
        btnAceptarConsultaMas = new javax.swing.JButton();
        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        inicio = new javax.swing.JMenu();
        listaClientes = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        nuevo = new javax.swing.JMenu();
        cliente = new javax.swing.JMenuItem();
        persona = new javax.swing.JMenuItem();
        mascota = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        registroCitas = new javax.swing.JMenuItem();
        Vacunaciones = new javax.swing.JMenuItem();
        historial = new javax.swing.JMenuItem();
        ayuda = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        Cliente.setTitle("Registro de Clientes");

        lblGenero.setText("Genero");

        lblCodigo.setText("DNI");

        cbGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sr.", "Sra." }));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        lblCliente.setText("Cliente");

        btnElimar.setText("Eliminar");
        btnElimar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElimarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ClienteLayout = new javax.swing.GroupLayout(Cliente.getContentPane());
        Cliente.getContentPane().setLayout(ClienteLayout);
        ClienteLayout.setHorizontalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(ClienteLayout.createSequentialGroup()
                        .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCliente)
                            .addComponent(lblGenero)
                            .addComponent(lblCodigo))
                        .addGap(36, 36, 36)
                        .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txtCliente)
                            .addComponent(cbGenero, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(ClienteLayout.createSequentialGroup()
                        .addComponent(btnAceptar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                        .addComponent(btnElimar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        ClienteLayout.setVerticalGroup(
            ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ClienteLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCodigo))
                .addGap(18, 18, 18)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGenero))
                .addGap(23, 23, 23)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCliente))
                .addGap(44, 44, 44)
                .addGroup(ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar)
                    .addComponent(btnElimar))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        Persona.setTitle("Registo de Personas");

        txtClientePer.setEnabled(false);

        jLabel1.setText("Nombre");

        jLabel2.setText("Apellidos");

        btnAceptarPersona.setText("Aceptar");
        btnAceptarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarPersonaActionPerformed(evt);
            }
        });

        jLabel3.setText("Direccion");

        btnCancelarPersona.setText("Cancelar");
        btnCancelarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarPersonaActionPerformed(evt);
            }
        });

        jLabel4.setText("Telefono");

        lblCliente1.setText("Cliente");

        btnAgregarCliente.setText("Agregar");
        btnAgregarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClienteActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(37, 142, 49));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblListaPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Nombre", "Apellido", "Direccion", "Telefono"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblListaPersona);

        btnBuscarPersona.setText("Buscar");
        btnBuscarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarPersonaActionPerformed(evt);
            }
        });

        btnEliminarPersona.setText("Eliminar");
        btnEliminarPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPersonaActionPerformed(evt);
            }
        });

        btnSiguientePersona.setText("Siguiente");
        btnSiguientePersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguientePersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(51, 51, 51)
                                .addComponent(btnBuscarPersona))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(btnEliminarPersona)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguientePersona)
                        .addGap(80, 80, 80))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarPersona))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarPersona)
                    .addComponent(btnSiguientePersona))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PersonaLayout = new javax.swing.GroupLayout(Persona.getContentPane());
        Persona.getContentPane().setLayout(PersonaLayout);
        PersonaLayout.setHorizontalGroup(
            PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(PersonaLayout.createSequentialGroup()
                        .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)
                                .addComponent(jLabel3)))
                        .addGap(199, 199, 199))
                    .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCliente1)
                        .addGroup(PersonaLayout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtClientePer, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDirecion, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(PersonaLayout.createSequentialGroup()
                                    .addComponent(btnAceptarPersona)
                                    .addGap(76, 76, 76)
                                    .addComponent(btnCancelarPersona))))))
                .addGap(18, 18, 18)
                .addComponent(btnAgregarCliente)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );
        PersonaLayout.setVerticalGroup(
            PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PersonaLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PersonaLayout.createSequentialGroup()
                        .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblCliente1)
                            .addComponent(txtClientePer, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAgregarCliente))
                        .addGap(18, 18, 18)
                        .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDirecion, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCancelarPersona)
                            .addComponent(btnAceptarPersona))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jLabel5.setText("Nombre de la Mascota");

        jLabel6.setText("Tipo de Animal");

        jLabel7.setText("Edad");

        txtClienteMas.setEnabled(false);

        btnAceptarMascota.setText("Aceptar");
        btnAceptarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarMascotaActionPerformed(evt);
            }
        });

        btnCancelarMascota.setText("Cancelar");
        btnCancelarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarMascotaActionPerformed(evt);
            }
        });

        jLabel8.setText("Cliente");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tblListaMascota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Mascota", "Tipo", "Edad"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblListaMascota);

        btnEliminarMascota.setText("Eliminar");
        btnEliminarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarMascotaActionPerformed(evt);
            }
        });

        btnFinalizarMascota.setText("Finalizar");
        btnFinalizarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarMascotaActionPerformed(evt);
            }
        });

        btnBuscarMascota.setText("Buscar");
        btnBuscarMascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarMascotaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnEliminarMascota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnFinalizarMascota)
                .addGap(87, 87, 87))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtBuscarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnBuscarMascota)
                .addContainerGap(67, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(24, 24, 24)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarMascota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminarMascota)
                    .addComponent(btnFinalizarMascota))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(37, Short.MAX_VALUE)))
        );

        cbEdad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Edad", "Meses", "Años" }));

        javax.swing.GroupLayout MascotaLayout = new javax.swing.GroupLayout(Mascota.getContentPane());
        Mascota.getContentPane().setLayout(MascotaLayout);
        MascotaLayout.setHorizontalGroup(
            MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MascotaLayout.createSequentialGroup()
                .addGroup(MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MascotaLayout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(btnAceptarMascota)
                        .addGap(89, 89, 89)
                        .addComponent(btnCancelarMascota))
                    .addGroup(MascotaLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtClienteMas, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(MascotaLayout.createSequentialGroup()
                                .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(cbEdad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(36, 36, 36)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MascotaLayout.setVerticalGroup(
            MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MascotaLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtClienteMas, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtNombreMascota, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtTipoAnimal, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptarMascota)
                    .addComponent(btnCancelarMascota))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(MascotaLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ListaCliente.setTitle("Lista de Clientes");

        tblListaCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Cliente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblListaCliente);

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAgregarCl.setText("Agregar");
        btnAgregarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarClActionPerformed(evt);
            }
        });

        btnCerrarCl.setText("Cerrar");
        btnCerrarCl.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarClActionPerformed(evt);
            }
        });

        lblTitulo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lblTitulo.setText("Lista de Clientes");

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ListaClienteLayout = new javax.swing.GroupLayout(ListaCliente.getContentPane());
        ListaCliente.getContentPane().setLayout(ListaClienteLayout);
        ListaClienteLayout.setHorizontalGroup(
            ListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaClienteLayout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(btnAgregarCl)
                .addGap(55, 55, 55)
                .addComponent(btnEliminar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarCl, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(137, 137, 137))
            .addGroup(ListaClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ListaClienteLayout.createSequentialGroup()
                        .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(btnBuscarCliente)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ListaClienteLayout.setVerticalGroup(
            ListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ListaClienteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTitulo)
                .addGap(16, 16, 16)
                .addGroup(ListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ListaClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEliminar)
                    .addComponent(btnAgregarCl)
                    .addComponent(btnCerrarCl))
                .addGap(20, 20, 20))
        );

        txtResultadoPersona.setColumns(20);
        txtResultadoPersona.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtResultadoPersona.setRows(5);
        jScrollPane4.setViewportView(txtResultadoPersona);

        lblTotulop.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTotulop.setText("Consulta de Persona");

        btnAceptarConsulta.setText("Aceptar");
        btnAceptarConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarConsultaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Consulta_PersonaLayout = new javax.swing.GroupLayout(Consulta_Persona.getContentPane());
        Consulta_Persona.getContentPane().setLayout(Consulta_PersonaLayout);
        Consulta_PersonaLayout.setHorizontalGroup(
            Consulta_PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Consulta_PersonaLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(lblTotulop)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Consulta_PersonaLayout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(Consulta_PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Consulta_PersonaLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Consulta_PersonaLayout.createSequentialGroup()
                        .addComponent(btnAceptarConsulta)
                        .addGap(41, 41, 41))))
        );
        Consulta_PersonaLayout.setVerticalGroup(
            Consulta_PersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Consulta_PersonaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTotulop)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptarConsulta)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        txtResultadoMascota.setColumns(20);
        txtResultadoMascota.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txtResultadoMascota.setRows(5);
        jScrollPane5.setViewportView(txtResultadoMascota);

        lblTotulo.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblTotulo.setText("Consulta de Persona");

        btnAceptarConsultaMas.setText("Aceptar");
        btnAceptarConsultaMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarConsultaMasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Consultar_MascotaLayout = new javax.swing.GroupLayout(Consultar_Mascota.getContentPane());
        Consultar_Mascota.getContentPane().setLayout(Consultar_MascotaLayout);
        Consultar_MascotaLayout.setHorizontalGroup(
            Consultar_MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Consultar_MascotaLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(lblTotulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Consultar_MascotaLayout.createSequentialGroup()
                .addContainerGap(31, Short.MAX_VALUE)
                .addGroup(Consultar_MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Consultar_MascotaLayout.createSequentialGroup()
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Consultar_MascotaLayout.createSequentialGroup()
                        .addComponent(btnAceptarConsultaMas)
                        .addGap(41, 41, 41))))
        );
        Consultar_MascotaLayout.setVerticalGroup(
            Consultar_MascotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Consultar_MascotaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblTotulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAceptarConsultaMas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        inicio.setText("Inicio");

        listaClientes.setText("Lista de Clientes");
        listaClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaClientesActionPerformed(evt);
            }
        });
        inicio.add(listaClientes);

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        inicio.add(exit);

        jMenuBar1.add(inicio);

        nuevo.setText("Nuevo");

        cliente.setText("Cliente");
        cliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clienteActionPerformed(evt);
            }
        });
        nuevo.add(cliente);

        persona.setText("Persona");
        persona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                personaActionPerformed(evt);
            }
        });
        nuevo.add(persona);

        mascota.setText("Mascota");
        mascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mascotaActionPerformed(evt);
            }
        });
        nuevo.add(mascota);

        jMenuBar1.add(nuevo);

        jMenu3.setText("Cita");

        registroCitas.setText("Registro de Citas");
        jMenu3.add(registroCitas);

        Vacunaciones.setText("Vacunacion");
        jMenu3.add(Vacunaciones);

        historial.setText("Historial Medico");
        jMenu3.add(historial);

        jMenuBar1.add(jMenu3);

        ayuda.setText("Ayuda");
        ayuda.setToolTipText("");

        about.setText("About");
        ayuda.add(about);

        jMenuBar1.add(ayuda);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitActionPerformed

    private void listaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaClientesActionPerformed
        
    }//GEN-LAST:event_listaClientesActionPerformed

    private void clienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clienteActionPerformed
        Cliente.setVisible(true);
        Cliente.setSize(340, 300);
        Cliente.setModal(true);
        Cliente.setLocationRelativeTo(null);
    }//GEN-LAST:event_clienteActionPerformed

    private void personaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_personaActionPerformed
        Persona.setVisible(true);
        Persona.setSize(920, 400);
        Persona.setModal(true);
        Persona.setLocationRelativeTo(null);
    }//GEN-LAST:event_personaActionPerformed

    private void mascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mascotaActionPerformed
        Mascota.setVisible(true);
        Mascota.setSize(900, 350);
        Mascota.setModal(true);
        Mascota.setLocationRelativeTo(null);
    }//GEN-LAST:event_mascotaActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        ArrayList<Cliente> lista = PersistenciaCliente.LoadData();
        Cliente cl = new Cliente();
        int genero = cbGenero.getSelectedIndex();
        String g;
        if(genero == 0){
            g = "Sr.";
        }else{
            g = "Sra.";
        }
        cl.setNombre(g + txtCliente.getText());
        cl.setCodigo(Integer.parseInt(txtCodigo.getText()));
        lista.add(cl);

        PersistenciaCliente.Savedata(lista);
        llenarCliente();
        
        Cliente.setVisible(false);
        Persona.setVisible(true);
        Persona.setSize(920, 400);
        Persona.setModal(true);
        Persona.setLocationRelativeTo(null);
        
        //Limpiamos los campos
        txtCliente.setText("");
        txtCodigo.setText("");
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        Cliente.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed
    String clien;
    private void btnAceptarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarPersonaActionPerformed
        ArrayList<Persona> lista = PersistenciaPersona.LoadData();
        Persona perso = new Persona();
        clien = txtClientePer.getText();
        perso.setNombre(txtNombre.getText());
        perso.setApellido(txtApellido.getText());
        perso.setDireccion(txtDirecion.getText());
        perso.setTelefono(Integer.parseInt(txtTelefono.getText()));
        lista.add(perso);
        
        PersistenciaPersona.Savedata(lista);
        llenarPersona();
        
        txtNombre.setText("");
        txtApellido.setText("");
        txtDirecion.setText("");
        txtTelefono.setText("");
        txtClientePer.setText("");
    }//GEN-LAST:event_btnAceptarPersonaActionPerformed

    private void btnCancelarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarPersonaActionPerformed
        Persona.setVisible(false);
    }//GEN-LAST:event_btnCancelarPersonaActionPerformed

    private void btnAgregarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClienteActionPerformed
        ListaCliente.setVisible(true);
        ListaCliente.setSize(450, 350);
        ListaCliente.setModal(true);
        ListaCliente.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnAgregarClienteActionPerformed

    private void btnAgregarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarClActionPerformed
        
        int fila = tblListaCliente.getSelectedRow();
        if(fila == -1){
            JOptionPane.showMessageDialog(null, "No ha selecionado ninguna fila","Avertencia",JOptionPane.WARNING_MESSAGE);
            
        }else{
            String cl = tblListaCliente.getValueAt(fila, 1).toString();
            txtClientePer.setText(cl);
            txtClienteMas.setText(cl);
            ListaCliente.setVisible(false);
        }
    }//GEN-LAST:event_btnAgregarClActionPerformed

    private void btnElimarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElimarActionPerformed
        ListaCliente.setVisible(true);
        ListaCliente.setSize(450, 350);
        ListaCliente.setModal(true);
        ListaCliente.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnElimarActionPerformed

    private void btnCerrarClActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarClActionPerformed
        ListaCliente.setVisible(false);
    }//GEN-LAST:event_btnCerrarClActionPerformed

    private void btnSiguientePersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguientePersonaActionPerformed
        Mascota.setVisible(true);
        Mascota.setSize(900, 350);
        Mascota.setModal(true);
        Mascota.setLocationRelativeTo(null);
        Persona.setVisible(false);
    }//GEN-LAST:event_btnSiguientePersonaActionPerformed

    private void btnAceptarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarMascotaActionPerformed
        ArrayList<Mascotas> lista = PersistenciaMascota.LoadData();
        Mascotas masco = new Mascotas();
        clien = txtClientePer.getText();
        masco.setNombre(txtNombreMascota.getText());
        masco.setTipoAnimal(txtTipoAnimal.getText());
        int mas= cbEdad.getSelectedIndex();
        String valor;
        if(mas == 1){
         valor="meses";   
        }else{
            valor="años";
        }
        masco.setEdad(txtEdad.getText()+" "+valor);
        lista.add(masco);
        
        PersistenciaMascota.Savedata(lista);
        llenarMascota();
        
        //Limpiamos los campos
        txtClienteMas.setText("");
        txtNombreMascota.setText("");
        txtTipoAnimal.setText("");
        txtEdad.setText("");

    }//GEN-LAST:event_btnAceptarMascotaActionPerformed

    private void btnCancelarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarMascotaActionPerformed
        Mascota.setVisible(false);
    }//GEN-LAST:event_btnCancelarMascotaActionPerformed

    private void btnEliminarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPersonaActionPerformed
        DefaultTableModel def = (DefaultTableModel) tblListaPersona.getModel();
        int eli = tblListaPersona.getSelectedRow();
        if(eli>=0){
            def.removeRow(eli);
        }else{
            JOptionPane.showMessageDialog(null, "Seleciones una fila");
        }
    }//GEN-LAST:event_btnEliminarPersonaActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        DefaultTableModel def = (DefaultTableModel) tblListaCliente.getModel();
        int eli = tblListaCliente.getSelectedRow();
        if(eli>=0){
            def.removeRow(eli);
        }else{
            JOptionPane.showMessageDialog(null, "Seleciones una fila");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnEliminarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarMascotaActionPerformed
        DefaultTableModel def = (DefaultTableModel) tblListaMascota.getModel();
        int eli = tblListaMascota.getSelectedRow();
        if(eli>=0){
            def.removeRow(eli);
        }else{
            JOptionPane.showMessageDialog(null, "Seleciones una fila");
        }
    }//GEN-LAST:event_btnEliminarMascotaActionPerformed

    private void btnFinalizarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarMascotaActionPerformed
        Mascota.setVisible(false);
    }//GEN-LAST:event_btnFinalizarMascotaActionPerformed

    private void btnBuscarPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarPersonaActionPerformed
        ArrayList<Persona> perso = PersistenciaPersona.LoadData();
        int busca = Integer.parseInt(txtBuscarPersona.getText());
        String resul = null;
        for(Persona d:perso){
            if(d.getTelefono() == busca){
                resul = "Persona: " + d.getNombre()+"\n"
                        + "Apellido: "+d.getApellido()+"\n"
                        + "Direccion: "+d.getDireccion()+"\n"
                        + "Telefono: "+d.getTelefono()+"\n";  
                Consulta_Persona.setVisible(true);
                Consulta_Persona.setSize(400, 350);
                Consulta_Persona.setModal(true);
                Consulta_Persona.setLocationRelativeTo(null);
                txtResultadoPersona.append(resul);
            }else{
                resul =  "No se encontro resultado";
                
            }JOptionPane.showMessageDialog(null, resul);
        }
        
        
    }//GEN-LAST:event_btnBuscarPersonaActionPerformed

    private void btnAceptarConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarConsultaActionPerformed
        txtResultadoPersona.setText("");
        Consulta_Persona.setVisible(false);
        
    }//GEN-LAST:event_btnAceptarConsultaActionPerformed

    private void btnBuscarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarMascotaActionPerformed
        
    }//GEN-LAST:event_btnBuscarMascotaActionPerformed

    private void btnAceptarConsultaMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarConsultaMasActionPerformed
        txtResultadoMascota.setText("");
        Consultar_Mascota.setVisible(false);
    }//GEN-LAST:event_btnAceptarConsultaMasActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
        ArrayList<Mascotas> masco = PersistenciaMascota.LoadData();
        String busca = txtBuscarMascota.getText();
        String resul = null;
        for(Mascotas m : masco){
            if(m.getNombre().equals(busca)){
                resul = "Nombre de la mascota: " + m.getNombre()+"\n"
                        + "Tipo de mascota: "+m.getTipoAnimal()+"\n"
                        + "Edad de la mascota: "+m.getEdad()+"\n";
                          
                Consultar_Mascota.setVisible(true);
                Consultar_Mascota.setSize(400, 350);
                Consultar_Mascota.setModal(true);
                Consultar_Mascota.setLocationRelativeTo(null);
                txtResultadoPersona.append(resul);
            }else{
                //resul =  "No se encontro resultado";
                JOptionPane.showMessageDialog(null, "Resultado no encontrado");
            }
        }
    }//GEN-LAST:event_btnBuscarClienteActionPerformed
    void limpiarCliente(){
        DefaultTableModel df = ((DefaultTableModel)tblListaCliente.getModel());
        int a = df.getRowCount()-1;
        for(int i=a;i>=0;i--){
            df.removeRow(i);
        }
    }
    
    void limpiarPersona(){
        DefaultTableModel df = ((DefaultTableModel)tblListaPersona.getModel());
        int a = df.getRowCount()-1;
        for(int i=a;i>=0;i--){
            df.removeRow(i);
        }
    }
    
    void limpiarMascota(){
        DefaultTableModel df = ((DefaultTableModel)tblListaMascota.getModel());
        int a = df.getRowCount()-1;
        for(int i=a;i>=0;i--){
            df.removeRow(i);
        }
    }
    
    void llenarCliente(){
        limpiarCliente();
        ArrayList<Cliente>lista = PersistenciaCliente.LoadData();
        DefaultTableModel df = ((DefaultTableModel)tblListaCliente.getModel());
        for (Cliente cl : lista) {
            df.addRow(new Object[]{cl.getCodigo(),cl.getNombre()});
        }
    }
    void llenarPersona(){
        limpiarPersona();
        ArrayList<Persona>lista = PersistenciaPersona.LoadData();
        DefaultTableModel df = ((DefaultTableModel)tblListaPersona.getModel());
        for (Persona perso : lista) {
            df.addRow(new Object[]{clien,perso.getNombre(),perso.getApellido(),perso.getDireccion(),perso.getTelefono()});
        }
    }
    void llenarMascota(){
        limpiarMascota();
        ArrayList<Mascotas>lista = PersistenciaMascota.LoadData();
        DefaultTableModel df = ((DefaultTableModel)tblListaMascota.getModel());
        for (Mascotas masco : lista) {
            df.addRow(new Object[]{clien,masco.getNombre(),masco.getTipoAnimal(),masco.getEdad()});
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVentana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog Cliente;
    private javax.swing.JDialog Consulta_Persona;
    private javax.swing.JDialog Consultar_Mascota;
    private javax.swing.JDialog ListaCliente;
    private javax.swing.JDialog Mascota;
    private javax.swing.JDialog Persona;
    private javax.swing.JMenuItem Vacunaciones;
    private javax.swing.JMenuItem about;
    private javax.swing.JMenu ayuda;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnAceptarConsulta;
    private javax.swing.JButton btnAceptarConsultaMas;
    private javax.swing.JButton btnAceptarMascota;
    private javax.swing.JButton btnAceptarPersona;
    private javax.swing.JButton btnAgregarCl;
    private javax.swing.JButton btnAgregarCliente;
    private javax.swing.JButton btnBuscarCliente;
    private javax.swing.JButton btnBuscarMascota;
    private javax.swing.JButton btnBuscarPersona;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarMascota;
    private javax.swing.JButton btnCancelarPersona;
    private javax.swing.JButton btnCerrarCl;
    private javax.swing.JButton btnElimar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarMascota;
    private javax.swing.JButton btnEliminarPersona;
    private javax.swing.JButton btnFinalizarMascota;
    private javax.swing.JButton btnSiguientePersona;
    private javax.swing.JComboBox cbEdad;
    private javax.swing.JComboBox cbGenero;
    private javax.swing.JMenuItem cliente;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuItem exit;
    private javax.swing.JMenuItem historial;
    private javax.swing.JMenu inicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblCliente;
    private javax.swing.JLabel lblCliente1;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblGenero;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTotulo;
    private javax.swing.JLabel lblTotulop;
    private javax.swing.JMenuItem listaClientes;
    private javax.swing.JMenuItem mascota;
    private javax.swing.JMenu nuevo;
    private javax.swing.JMenuItem persona;
    private javax.swing.JMenuItem registroCitas;
    private javax.swing.JTable tblListaCliente;
    private javax.swing.JTable tblListaMascota;
    private javax.swing.JTable tblListaPersona;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtBuscarMascota;
    private javax.swing.JTextField txtBuscarPersona;
    private javax.swing.JTextField txtCliente;
    private javax.swing.JTextField txtClienteMas;
    private javax.swing.JTextField txtClientePer;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDirecion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreMascota;
    private javax.swing.JTextArea txtResultadoMascota;
    private javax.swing.JTextArea txtResultadoPersona;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTipoAnimal;
    // End of variables declaration//GEN-END:variables
}
